function [mean_x mean_y] = readDiemEyeMovementsForSubjects(movie_name, subjects)

path = '/Users/pkmital/diem/data/DIEM/event_data/';
% movie_names = getDiemMovieNames(diem_number);
[width height] = getDiemMovieSize(movie_name);

[mean_x mean_y] = ...
        getBinocularDistributionForSubjects(path,       ...
                                 movie_name,        ...
                                 width,  ...
                                 height, ...
                                 subjects);

