function [features feature_tags feature_values] = ...
    getDiemCinematicFeatures(diem_number)

if(nargin == 0)
    diem_number = 1;
end

feature_dir = ['/Users/pkmital/diem/data/DIEM/cinematic_features/diem' num2str(diem_number)];
files = dir([feature_dir '/*.txt']);
features{length(files)} = {};

feature_tags = {'Frame Number', 'Screens', 'Image Type', 'Edit Type', 'Shot Size', ...
    'Cam Mount', 'Cam Angle', 'Cam Roll', 'Cam Movement', ...
    'Cam Speed', 'Film Speed'};

feature_values = {...
    {}, ...
    {'1', '2', '3', '4', '5', '6', '>6', 'NA'}, ...
    {'Live Action', 'Animation', 'Graphic', 'Text', 'Abstract', 'Multiple', 'Other', 'NA'}, ...
    {'Cut', 'Fade', 'Dissolve', 'Wipe', 'Whip Pan', 'Digital', 'Other', 'None'}, ...
    {'XCU', 'CU', 'CMS', 'MS', 'MLS', 'LS', 'XLS', 'NA'}, ...
    {'Tripod', 'Steadicam', 'Hand-held', 'Vehicle', 'Aircraft', 'Unknown', 'NA'}, ...
    {'Worms Eye', 'Low', 'Eye-level', 'High', 'Birds Eye', 'Unknown', 'NA'}, ...
    {'Level', 'Slight', 'Side-on', 'Upside-down', 'Changing', 'NA'}, ...
    {'Horizontal', 'Vertical', 'Forwards', 'Backwards', 'Pan', 'Tilt', 'Zoom In', 'Zoom Out', 'Complex', 'None', 'NA'}, ...
    {'None', 'Slow', 'Medium', 'Fast', 'Blur', 'NA'}, ...
    {'Very Slow', 'Slow', 'Real-time', 'Fast', 'Very Fast', 'NA'} };

for file_i = 1 : length(files);
    fid = fopen([feature_dir '/' files(file_i).name]);
    features{file_i} = textscan(fid, '%d %d %d %d %d %d %d %d %d %d %d');
    fclose(fid);
end
