% processKLDivergence('news_bee_parasites')
% processKLDivergence('news_sherry_drinking_mice')
% processKLDivergence('news_us_election_debate')
% processKLDivergence('news_video_republic')
% processKLDivergence('news_wimbledon_macenroe')
% processKLDivergence('documentary_adrenaline_rush')
% processKLDivergence('documentary_coral_reef_adventure')
% % %processKLDivergence('documentary_discoverers')
% processKLDivergence('documentary_dolphins')
% processKLDivergence('documentary_mystery_nile')
% processKLDivergence('documentary_planet_earth')
% processKLDivergence('movie_trailer_quantum_of_solace')
%processKLDivergence('music_trailer_nine_inch_nails')
% processKLDivergence('home_movie_Charlie_bit_my_finger_again')
% % processKLDivergence('movie_trailer_ice_age_3')
% processKLDivergence('advert_bbc4_bees')
% processKLDivergence('advert_bbc4_library')
% processKLDivergence('advert_bravia')
% processKLDivergence('advert_iphone')
% processKLDivergence('game_trailer_bullet_witch')
% processKLDivergence('game_trailer_ghostbusters')
% processKLDivergence('game_trailer_lego_indiana_jones')
% processKLDivergence('game_trailer_wrath_lich_king_shortened_subtitles')
% processKLDivergence('music_gummybear')
processKLDivergence('music_red_hot_chili_peppers_shortened')
processKLDivergence('university_forum_construction_ionic')